<?php

/* 
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *  This API has now modified by VeoZax under GNU Lesser General Public License.
 *  Feel free to use it + if you are willing to modify or Enhance this API,
 *  Make sure to publish your changes to the GitHub open sourced.
 *  Do Not Own This API Privately Since this API is made to use Freely for Every
 *  Legacy users from 0.14.x - 0.15.10 - 1.1.x
 *   
 *               ╦  ╦┌─┐┌─┐╔═╗┌─┐─┐ ┬  ╔═╗┌─┐┬
 *               ╚╗╔╝├┤ │ │╔═╝├─┤┌┴┬┘  ╠═╣├─┘│
 *                ╚╝ └─┘└─┘╚═╝┴ ┴┴ └─  ╩ ╩┴  ┴
 *  
 *  	         » Multi-Version API by VeoZax 
 *             » Accepted MCPE Versions: 0.14x - 0.15.10 - 1.1.x
 *  			     » YouTube: @VeoZax
 *            » Discord: https://discord.gg/dCzgPYam2J
 *               » Website: https://info.veozax.xyz
 */


declare(strict_types=1);
namespace pocketmine\network\mcpe\multiversion\constants;
use pocketmine\network\mcpe\protocol\ProtocolInfo;
final class LevelSoundIds{
	private function __construct(){
	}
	public const LEVEL_SOUND_IDS = [
                                										ProtocolInfo::PROTOCOL_110 => [
			"SOUND_ITEM_USE_ON" => 0,
			"SOUND_HIT" => 1,
			"SOUND_STEP" => 2,
			"SOUND_JUMP" => 3,
			"SOUND_BREAK" => 4,
			"SOUND_PLACE" => 5,
			"SOUND_HEAVY_STEP" => 6,
			"SOUND_GALLOP" => 7,
			"SOUND_FALL" => 8,
			"SOUND_AMBIENT" => 9,
			"SOUND_AMBIENT_BABY" => 10,
			"SOUND_AMBIENT_IN_WATER" => 11,
			"SOUND_BREATHE" => 12,
			"SOUND_DEATH" => 13,
			"SOUND_DEATH_IN_WATER" => 14,
			"SOUND_DEATH_TO_ZOMBIE" => 15,
			"SOUND_HURT" => 16,
			"SOUND_HURT_IN_WATER" => 17,
			"SOUND_MAD" => 18,
			"SOUND_BOOST" => 19,
			"SOUND_BOW" => 20,
			"SOUND_SQUISH_BIG" => 21,
			"SOUND_SQUISH_SMALL" => 22,
			"SOUND_FALL_BIG" => 23,
			"SOUND_FALL_SMALL" => 24,
			"SOUND_SPLASH" => 25,
			"SOUND_FIZZ" => 26,
			"SOUND_FLAP" => 27,
			"SOUND_SWIM" => 28,
			"SOUND_DRINK" => 29,
			"SOUND_EAT" => 30,
			"SOUND_TAKEOFF" => 31,
			"SOUND_SHAKE" => 32,
			"SOUND_PLOP" => 33,
			"SOUND_LAND" => 34,
			"SOUND_SADDLE" => 35,
			"SOUND_ARMOR" => 36,
			"SOUND_ADD_CHEST" => 37,
			"SOUND_THROW" => 38,
			"SOUND_ATTACK" => 39,
			"SOUND_ATTACK_NODAMAGE" => 40,
			"SOUND_WARN" => 41,
			"SOUND_SHEAR" => 42,
			"SOUND_MILK" => 43,
			"SOUND_THUNDER" => 44,
			"SOUND_EXPLODE" => 45,
			"SOUND_FIRE" => 46,
			"SOUND_IGNITE" => 47,
			"SOUND_FUSE" => 48,
			"SOUND_STARE" => 49,
			"SOUND_SPAWN" => 50,
			"SOUND_SHOOT" => 51,
			"SOUND_BREAK_BLOCK" => 52,
			"SOUND_REMEDY" => 53,
			"SOUND_UNFECT" => 54,
			"SOUND_LEVELUP" => 55,
			"SOUND_BOW_HIT" => 56,
			"SOUND_BULLET_HIT" => 57,
			"SOUND_EXTINGUISH_FIRE" => 58,
			"SOUND_ITEM_FIZZ" => 59,
			"SOUND_CHEST_OPEN" => 60,
			"SOUND_CHEST_CLOSED" => 61,
			"SOUND_SHULKERBOX_OPEN" => 62,
			"SOUND_SHULKERBOX_CLOSED" => 63,
			"SOUND_POWER_ON" => 64,
			"SOUND_POWER_OFF" => 65,
			"SOUND_ATTACH" => 66,
			"SOUND_DETACH" => 67,
			"SOUND_DENY" => 68,
			"SOUND_TRIPOD" => 69,
			"SOUND_POP" => 70,
			"SOUND_DROP_SLOT" => 71,
			"SOUND_NOTE" => 72,
			"SOUND_THORNS" => 73,
			"SOUND_PISTON_IN" => 74,
			"SOUND_PISTON_OUT" => 75,
			"SOUND_PORTAL" => 76,
			"SOUND_WATER" => 77,
			"SOUND_LAVA_POP" => 78,
			"SOUND_LAVA" => 79,
			"SOUND_BURP" => 80,
			"SOUND_BUCKET_FILL_WATER" => 81,
			"SOUND_BUCKET_FILL_LAVA" => 82,
			"SOUND_BUCKET_EMPTY_WATER" => 83,
			"SOUND_BUCKET_EMPTY_LAVA" => 84,
			"SOUND_FLOP" => 85,
			"SOUND_ELDERGUARDIAN_CURSE" => 86,
			"SOUND_MOB_WARNING" => 87,
			"SOUND_MOB_WARNING_BABY" => 88,
			"SOUND_TELEPORT" => 89,
			"SOUND_SHULKER_OPEN" => 90,
			"SOUND_SHULKER_CLOSE" => 91,
			"SOUND_HAGGLE" => 92,
			"SOUND_HAGGLE_YES" => 93,
			"SOUND_HAGGLE_NO" => 94,
			"SOUND_HAGGLE_IDLE" => 95,
			"SOUND_CHORUSGROW" => 96,
			"SOUND_CHORUSDEATH" => 97,
			"SOUND_GLASS" => 98,
			"SOUND_CAST_SPELL" => 99,
			"SOUND_PREPARE_ATTACK" => 100,
			"SOUND_PREPARE_SUMMON" => 101,
			"SOUND_PREPARE_WOLOLO" => 102,
			"SOUND_FANG" => 103,
			"SOUND_CHARGE" => 104,
			"SOUND_CAMERA_TAKE_PICTURE" => 105,
			"SOUND_DEFAULT" => 106,
			"SOUND_UNDEFINED" => 107
		],
		ProtocolInfo::PROTOCOL_41 => [
			"SOUND_ITEM_USE_ON" => 0,
			"SOUND_HIT" => 1,
			"SOUND_STEP" => 2,
			"SOUND_JUMP" => 3,
			"SOUND_BREAK" => 4,
			"SOUND_PLACE" => 5,
			"SOUND_HEAVY_STEP" => 6,
			"SOUND_GALLOP" => 7,
			"SOUND_FALL" => 8,
			"SOUND_AMBIENT" => 9,
			"SOUND_AMBIENT_BABY" => 10,
			"SOUND_AMBIENT_IN_WATER" => 11,
			"SOUND_BREATHE" => 12,
			"SOUND_DEATH" => 13,
			"SOUND_DEATH_IN_WATER" => 14,
			"SOUND_DEATH_TO_ZOMBIE" => 15,
			"SOUND_HURT" => 16,
			"SOUND_HURT_IN_WATER" => 17,
			"SOUND_MAD" => 18,
			"SOUND_BOOST" => 19,
			"SOUND_BOW" => 20,
			"SOUND_SQUISH_BIG" => 21,
			"SOUND_SQUISH_SMALL" => 22,
			"SOUND_FALL_BIG" => 23,
			"SOUND_FALL_SMALL" => 24,
			"SOUND_SPLASH" => 25,
			"SOUND_FIZZ" => 26,
			"SOUND_FLAP" => 27,
			"SOUND_SWIM" => 28,
			"SOUND_DRINK" => 29,
			"SOUND_EAT" => 30,
			"SOUND_TAKEOFF" => 31,
			"SOUND_SHAKE" => 32,
			"SOUND_PLOP" => 33,
			"SOUND_LAND" => 34,
			"SOUND_SADDLE" => 35,
			"SOUND_ARMOR" => 36,
			"SOUND_ADD_CHEST" => 37,
			"SOUND_THROW" => 38,
			"SOUND_ATTACK" => 39,
			"SOUND_ATTACK_NODAMAGE" => 40,
			"SOUND_WARN" => 41,
			"SOUND_SHEAR" => 42,
			"SOUND_MILK" => 43,
			"SOUND_THUNDER" => 44,
			"SOUND_EXPLODE" => 45,
			"SOUND_FIRE" => 46,
			"SOUND_IGNITE" => 47,
			"SOUND_FUSE" => 48,
			"SOUND_STARE" => 49,
			"SOUND_SPAWN" => 50,
			"SOUND_SHOOT" => 51,
			"SOUND_BREAK_BLOCK" => 52,
			"SOUND_REMEDY" => 53,
			"SOUND_UNFECT" => 54,
			"SOUND_LEVELUP" => 55,
			"SOUND_BOW_HIT" => 56,
			"SOUND_BULLET_HIT" => 57,
			"SOUND_EXTINGUISH_FIRE" => 58,
			"SOUND_ITEM_FIZZ" => 59,
			"SOUND_CHEST_OPEN" => 60,
			"SOUND_CHEST_CLOSED" => 61,
			"SOUND_POWER_ON" => 62,
			"SOUND_POWER_OFF" => 63,
			"SOUND_ATTACH" => 64,
			"SOUND_DETACH" => 65,
			"SOUND_DENY" => 66,
			"SOUND_TRIPOD" => 67,
			"SOUND_POP" => 68,
			"SOUND_DROP_SLOT" => 69,
			"SOUND_NOTE" => 70,
			"SOUND_THORNS" => 71,
			"SOUND_PISTON_IN" => 72,
			"SOUND_PISTON_OUT" => 73,
			"SOUND_PORTAL" => 74,
			"SOUND_WATER" => 75,
			"SOUND_LAVA_POP" => 76,
			"SOUND_LAVA" => 77,
			"SOUND_BURP" => 78,
			"SOUND_BUCKET_FILL_WATER" => 79,
			"SOUND_BUCKET_FILL_LAVA" => 80,
			"SOUND_BUCKET_EMPTY_WATER" => 81,
			"SOUND_BUCKET_EMPTY_LAVA" => 82,
			"SOUND_GUARDIAN_FLOP" => 83,
			"SOUND_MOB_ELDERGUARDIAN_CURSE" => 84,
			"SOUND_MOB_WARNING" => 85,
			"SOUND_MOB_WARNING_BABY" => 86,
			"SOUND_TELEPORT" => 87,
			"SOUND_SHULKER_OPEN" => 88,
			"SOUND_SHULKER_CLOSE" => 89,
			"SOUND_HAGGLE" => 90,
			"SOUND_HAGGLE_YES" => 91,
			"SOUND_HAGGLE_NO" => 92,
			"SOUND_HAGGLE_IDLE" => 93,
			"SOUND_CHORUSGROW" => 94,
			"SOUND_CHORUSDEATH" => 95,
			"SOUND_DEFAULT" => 96,
			"SOUND_UNDEFINED" => 97
		]
	];}